grails-app/domain/time/nucleus/api/RegisteredApplication.groovy
package time.nucleus.api

/**
 * This class defines the websites that will have access to the Time-Nucleus API
 *
 */

class RegisteredApplication {

    String name
    String apiKey = generateRandomApiKey()

    boolean active

    Date dateCreated
    Date lastUpdated

    String authorizedMethods = null

    static hasMany = [requestLogs: RequestLog]

    static constraints = {
        name blank: false
        apiKey nullable: false, unique: true
        authorizedMethods nullable: true
    }

    static mapping = {
        version false
    }


    /**
     *
     * @return
     */
    def generateRandomApiKey() {

        String CHARACTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789&#@+-=!"
        int API_KEY_SIZE = 32

        String apiKey = "";

        def random = new Random()
        def randomPos

        int nbAvailableChars = CHARACTERS.length()

        32.times() {
            randomPos = random.nextInt(nbAvailableChars)
            apiKey += CHARACTERS[randomPos]
        }

        return apiKey
    }

}

grails-app/domain/time/nucleus/security/User.groovy
package time.nucleus.security

import time.nucleus.hotels.Hotel

class User {

	transient springSecurityService

	String username
    String lastName
    String firstName
    String email

	String password
	boolean enabled
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

    Date dateCreated
    Date lastUpdated


    static hasMany = [hotels : Hotel]

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}

    List<Hotel>  getHotelsNotManagedByUser() {
        return Hotel.list() - this.hotels
    }
}

grails-app/controllers/time/nucleus/HomeController.groovy
package time.nucleus

import grails.plugins.springsecurity.Secured
@Secured(['ROLE_HOTEL'])
class HomeController {
    def availabilityService
    def springSecurityService

    def index() {
        def currentHotel = null
        def currentUser = springSecurityService.getCurrentUser()
        // If the user has at least one hotel
        // We pass it to the view in order to populate
        // the rooms menu
        if (currentUser?.hotels){
            currentHotel = currentUser.hotels.first()
        }
       [activeMenuID:"dashboard", user:springSecurityService.getCurrentUser(), hotelInstance:currentHotel]
    }
}

grails-app/views/layouts/sidebar/_sidebar.gsp
<!-- START SIDEBAR -->
<div id="sidebar">
    <div id="sidemenu">
        <ul>
            <li id="dashboard">
                <g:link controller="home" action="index">
                    <r:img dir="images/icons/sidemenu/" file="laptop.png" width="16" height="16" alt="icon" />
                    Tableau de bord
                </g:link>
            </li>
            <g:if test="user.hotels" >
                <g:each in="${user?.hotels?.sort{it.id}}" >
                    <g:render template="/layouts/sidebar/sidebarHotel" model="['hotel':it]"/>
                </g:each>
            </g:if>
            <sec:ifAnyGranted roles="ROLE_CONTENT_EDITOR">
                <li class="subtitle">
                    <a class="action tips-right" href="#" original-title="Hotels">
                        <r:img dir="images/icons/sidemenu/" file="copy.png" width="16" height="16" alt="icon" />
                        Hotels
                        <r:img dir="images/" file="arrow-down.png" width="7" height="4" alt="arrow" class="arrow" />
                    </a>
                    <ul class="submenu" style="display: none;">
                        <li id="hotelList">
                            <g:link controller="hotel" action="list">
                            <r:img dir="images/icons/sidemenu/" file="list.png" width="16" height="16" alt="icon" />
                            Liste des Hôtels
                            </g:link>
                        </li>
                        <li id="hotelCreate">
                            <g:link controller="hotel" action="create">
                                <r:img dir="images/icons/sidemenu/" file="file_add.png" width="16" height="16" alt="icon" />
                                Ajouter un Hôtel
                            </g:link>
                        </li>
                    </ul>
                </li>
            </sec:ifAnyGranted>
            <sec:ifAnyGranted roles="ROLE_ADMIN">
                <li class="subtitle">
                    <a class="action tips-right" href="#" original-title="Applications">
                        <r:img dir="images/icons/sidemenu/" file="copy.png" width="16" height="16" alt="icon" />
                        Applications
                        <r:img dir="images/" file="arrow-down.png" width="7" height="4" alt="arrow" class="arrow" />
                    </a>
                    <ul class="submenu" style="display: none;">
                        <li id="applicationList">
                            <g:link controller="registeredApplication" action="list">
                                <r:img dir="images/icons/sidemenu/" file="list.png" width="16" height="16" alt="icon" />
                                Liste des applications
                            </g:link>
                        </li>
                        <li id="applicationCreate">
                            <g:link controller="registeredApplication" action="create">
                                <r:img dir="images/icons/sidemenu/" file="file_add.png" width="16" height="16" alt="icon" />
                                Ajouter une application
                            </g:link>
                        </li>
                    </ul>
                </li>
                <li class="subtitle">
                    <a class="action tips-right" href="#" original-title="Users">
                        <r:img dir="images/icons/sidemenu/" file="copy.png" width="16" height="16" alt="icon" />
                        Utilisateurs
                        <r:img dir="images/" file="arrow-down.png" width="7" height="4" alt="arrow" class="arrow" />
                    </a>
                    <ul class="submenu" style="display: none;">
                        <li id="userList">
                            <g:link controller="user" action="list">
                                <r:img dir="images/icons/sidemenu/" file="list.png" width="16" height="16" alt="icon" />
                                Liste des utilisateurs
                            </g:link>
                        </li>
                        <li id="userCreate">
                            <g:link controller="user" action="create">
                                <r:img dir="images/icons/sidemenu/" file="file_add.png" width="16" height="16" alt="icon" />
                                Ajouter un utilisateur
                            </g:link>
                        </li>
                    </ul>
                </li>
            </sec:ifAnyGranted>
            <sec:ifAnyGranted roles="ROLE_ADMIN, ROLE_CONTENT_EDITOR">
                <g:if test="${registeredApplicationInstance}">
                    <g:render template="/layouts/sidebar/sidebarApplication" model="['registeredApplicationInstance':registeredApplicationInstance]"/>
                </g:if>
                <g:if test="${hotelInstance}">
                    <g:render template="/layouts/sidebar/sidebarHotel" model="['hotel':hotelInstance]"/>
                </g:if>
                <g:if test="${userInstance}">
                    <g:render template="/layouts/sidebar/sidebarUser" model="['userInstance':userInstance]"/>
                </g:if>
            </sec:ifAnyGranted>
        </ul>
    </div>
</div>  <!-- END SIDEBAR -->

grails-app/views/layouts/sidebar/_sidebarApplication.gsp
<li id="application${registeredApplicationInstance.id}">
    <g:link controller="registeredApplication" action="show" id="${registeredApplicationInstance.id}">
    ${registeredApplicationInstance.name}
    </g:link>
</li>

grails-app/views/layouts/sidebar/_sidebarHotel.gsp
<li class="subtitle" id="hotels${hotel.id}">
    <a class="action tips-right" href="#" original-title="Cliquez ici pour ouvrir le menu de l'établissement">
        <r:img dir="images/icons/sidemenu/" file="copy.png" width="16" height="16" alt="icon" />
        ${hotel.name}
        <r:img dir="images/" file="arrow-down.png" width="7" height="4" alt="arrow" class="arrow" />
    </a>
    <ul class="submenu" style="display: none;">
        <li id="ficheHotel${hotel.id}">
            <g:link controller="hotel" action="show" id="${hotel.id}" class="tips-right" original-title="Editez les informations de l'établissement ${hotel.name}">
                <r:img dir="images/icons/sidemenu/" file="vcard.png" width="16" height="16" alt="icon"/>
                Fiche hôtel
            </g:link>
        </li>
        <li id="ajouterChambre${hotel.id}">
            <g:link controller="room" params="[hotel:hotel.id]"  action="create" class="tips-right" original-title="Cliquez ici pour ajouter une nouvelle chambre à votre établissement" >
                <r:img dir="images/icons/sidemenu/" file="file_add.png" width="16" height="16" alt="icon"/>
                Ajouter une chambre
            </g:link>
        </li>
        <li id="gestionAllotement${hotel.id}">
            <g:link controller="availability" params="[hotel:hotel.id]"  action="index" class="tips-right" original-title="Cliquez ici pour gérer l'allotement de vos chambres" >
                <r:img dir="images/icons/sidemenu/" file="calendar.png" width="16" height="16" alt="icon"/>
                Allotement
            </g:link>
        </li>
        <li>
            <a href="#">
            </a>
        </li>
        <g:each in="${hotel.rooms.sort{it.name}}" >
            <li id="hotel${hotel.id}room${it.id}">
                <g:link controller="room" action="show" id="${it.id}">
                    <r:img dir="images/icons/sidemenu/" file="image.png" width="16" height="16" alt="icon"/>
                    ${it.name}
                </g:link>
            </li>
        </g:each>
    </ul>
</li>

grails-app/views/layouts/sidebar/_sidebarUser.gsp
<li id="user${userInstance.id}">
    <g:link controller="user" action="show" id="${userInstance.id}">
        ${userInstance.lastName} ${userInstance.firstName}
    </g:link>
</li>